let JSONdata=
{
    "Datas": {
        "MaxPortLevel": 6,
        "BestInvest": 4,
        "PortList": [{
                "ModelID": "0101",
                "ModelOrder": 1,
                "AssetID": "01",
                "AssetName": "股票",
                "AssetWgt": 15.0
            }, {
                "ModelID": "0101",
                "ModelOrder": 1,
                "AssetID": "02",
                "AssetName": "債券",
                "AssetWgt": 85.0
            }, {
                "ModelID": "0102",
                "ModelOrder": 2,
                "AssetID": "01",
                "AssetName": "股票",
                "AssetWgt": 20.0
            }, {
                "ModelID": "0102",
                "ModelOrder": 2,
                "AssetID": "02",
                "AssetName": "債券",
                "AssetWgt": 80.0
            }, {
                "ModelID": "0103",
                "ModelOrder": 3,
                "AssetID": "01",
                "AssetName": "股票",
                "AssetWgt": 30.0
            }, {
                "ModelID": "0103",
                "ModelOrder": 3,
                "AssetID": "02",
                "AssetName": "債券",
                "AssetWgt": 70.0
            }, {
                "ModelID": "0104",
                "ModelOrder": 4,
                "AssetID": "01",
                "AssetName": "股票",
                "AssetWgt": 40.0
            }, {
                "ModelID": "0104",
                "ModelOrder": 4,
                "AssetID": "02",
                "AssetName": "債券",
                "AssetWgt": 60.0
            }, {
                "ModelID": "0105",
                "ModelOrder": 5,
                "AssetID": "01",
                "AssetName": "股票",
                "AssetWgt": 50.0
            }, {
                "ModelID": "0105",
                "ModelOrder": 5,
                "AssetID": "02",
                "AssetName": "債券",
                "AssetWgt": 50.0
            }, {
                "ModelID": "0106",
                "ModelOrder": 6,
                "AssetID": "01",
                "AssetName": "股票",
                "AssetWgt": 60.0
            }, {
                "ModelID": "0106",
                "ModelOrder": 6,
                "AssetID": "02",
                "AssetName": "債券",
                "AssetWgt": 40.0
            }, {
                "ModelID": "0107",
                "ModelOrder": 7,
                "AssetID": "01",
                "AssetName": "股票",
                "AssetWgt": 70.0
            }, {
                "ModelID": "0107",
                "ModelOrder": 7,
                "AssetID": "02",
                "AssetName": "債券",
                "AssetWgt": 30.0
            }, {
                "ModelID": "0108",
                "ModelOrder": 8,
                "AssetID": "01",
                "AssetName": "股票",
                "AssetWgt": 80.0
            }, {
                "ModelID": "0108",
                "ModelOrder": 8,
                "AssetID": "02",
                "AssetName": "債券",
                "AssetWgt": 20.0
            }, {
                "ModelID": "0109",
                "ModelOrder": 9,
                "AssetID": "01",
                "AssetName": "股票",
                "AssetWgt": 90.0
            }, {
                "ModelID": "0109",
                "ModelOrder": 9,
                "AssetID": "02",
                "AssetName": "債券",
                "AssetWgt": 10.0
            }, {
                "ModelID": "0110",
                "ModelOrder": 10,
                "AssetID": "01",
                "AssetName": "股票",
                "AssetWgt": 100.0
            }, {
                "ModelID": "0110",
                "ModelOrder": 10,
                "AssetID": "02",
                "AssetName": "債券",
                "AssetWgt": 0.0
            }
        ]
    },
    "Message": "",
    "MessageType": "04",
    "ResultCode": "01"
}
module.exports = JSONdata