let JSONdata={
    "Datas": {
        "AssetAllocate": [{
                "AssetID": "01",
                "AssetName": "股票",
                "AssetWgt": 40.0
            }, {
                "AssetID": "02",
                "AssetName": "債券",
                "AssetWgt": 60.0
            }
        ],
        "CateAllocate": [{
                "CategoryID": "01",
                "CategoryName": "亞太（日本除外）股票",
                "AssetID": "01",
                "CategoryWgt": 0.0
            }, {
                "CategoryID": "02",
                "CategoryName": "亞洲債券",
                "AssetID": "02",
                "CategoryWgt": 0.0
            }, {
                "CategoryID": "04",
                "CategoryName": "現金",
                "AssetID": "03",
                "CategoryWgt": 0.0
            }, {
                "CategoryID": "05",
                "CategoryName": "新興市場債券",
                "AssetID": "02",
                "CategoryWgt": 0.0
            }, {
                "CategoryID": "06",
                "CategoryName": "新興市場股票",
                "AssetID": "01",
                "CategoryWgt": 0.0
            }, {
                "CategoryID": "07",
                "CategoryName": "歐洲股票",
                "AssetID": "01",
                "CategoryWgt": 0.0
            }, {
                "CategoryID": "08",
                "CategoryName": "全球債券",
                "AssetID": "02",
                "CategoryWgt": 0.0
            }, {
                "CategoryID": "09",
                "CategoryName": "全球高收益債券",
                "AssetID": "02",
                "CategoryWgt": 0.0
            }, {
                "CategoryID": "10",
                "CategoryName": "全球房地產投資信託",
                "AssetID": "04",
                "CategoryWgt": 0.0
            }, {
                "CategoryID": "12",
                "CategoryName": "日本股票",
                "AssetID": "01",
                "CategoryWgt": 0.0
            }, {
                "CategoryID": "13",
                "CategoryName": "其他替代品",
                "AssetID": "04",
                "CategoryWgt": 0.0
            }, {
                "CategoryID": "15",
                "CategoryName": "台灣股票",
                "AssetID": "01",
                "CategoryWgt": 0.0
            }, {
                "CategoryID": "16",
                "CategoryName": "美國股票",
                "AssetID": "01",
                "CategoryWgt": 0.0
            }
        ],
        "PrdAllocate": [{
                "PrdID": "P06",
                "PrdName": "商品06",
                "PrdWgt": 2.000000
            }, {
                "PrdID": "P01",
                "PrdName": "商品01",
                "PrdWgt": 12.000000
            }, {
                "PrdID": "P12",
                "PrdName": "商品12",
                "PrdWgt": 3.000000
            }, {
                "PrdID": "P02",
                "PrdName": "商品02",
                "PrdWgt": 11.000000
            }, {
                "PrdID": "P07",
                "PrdName": "商品07",
                "PrdWgt": 1.000000
            }, {
                "PrdID": "P08",
                "PrdName": "商品08",
                "PrdWgt": 5.000000
            }, {
                "PrdID": "P03",
                "PrdName": "商品03",
                "PrdWgt": 19.000000
            }, {
                "PrdID": "P04",
                "PrdName": "商品04",
                "PrdWgt": 24.000000
            }, {
                "PrdID": "P05",
                "PrdName": "商品05",
                "PrdWgt": 8.000000
            }, {
                "PrdID": "P09",
                "PrdName": "商品09",
                "PrdWgt": 1.000000
            }, {
                "PrdID": "P13",
                "PrdName": "商品13",
                "PrdWgt": 8.000000
            }, {
                "PrdID": "P10",
                "PrdName": "商品10",
                "PrdWgt": 1.000000
            }, {
                "PrdID": "P11",
                "PrdName": "商品11",
                "PrdWgt": 5.000000
            }
        ]
    },
    "Message": "",
    "MessageType": "04",
    "ResultCode": "01"
}
module.exports = JSONdata